# Generated by Django 4.2 on 2023-04-17 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='Finch',
            new_name='finch',
        ),
    ]
